# v_core/domains/orchestration/state_machine.py
from enum import Enum
from v_core.domains.tools.preconditions import SecurityTier
import httpx
import json

class Orchestrator:
    """
    The main execution loop. It manages memory sensors, triggers compaction, 
    evaluates tool preconditions, and enforces blast gates.
    """
    def __init__(self, ram_window, compaction_engine, tool_registry):
        self.ram = ram_window
        self.compaction = compaction_engine
        self.tools = tool_registry

    # ---------------------------------------------------------
    # METHOD 1: The LLM Bridge (Independent Class Method)
    # ---------------------------------------------------------
    async def _call_qwen_llm(self, context: list) -> dict:
        """
        The actual execution bridge to local Ollama.
        Forces strict JSON output to guarantee structural integrity for the state machine.
        """
        ollama_url = "http://localhost:11434/api/chat"
        
        payload = {
            "model": "qwen2.5",
            "messages": context,
            "stream": False,
            "format": "json"  # Enforces deterministic JSON parsing
        }

        async with httpx.AsyncClient(timeout=120.0) as client:
            try:
                response = await client.post(ollama_url, json=payload)
                response.raise_for_status()
                data = response.json()
                
                # Extract the message content generated by Qwen
                content_str = data.get("message", {}).get("content", "{}")
                parsed_content = json.loads(content_str)
                
                return {
                    "text": parsed_content.get("text", ""),
                    "tool_call": parsed_content.get("tool_call", None)
                }
                
            except httpx.RequestError as e:
                return {"text": f"SYSTEM_ERROR: Connection to Ollama failed. {str(e)}", "tool_call": None}
            except json.JSONDecodeError:
                return {"text": "SYSTEM_ERROR: Model hallucinated invalid JSON.", "tool_call": None}

    # ---------------------------------------------------------
    # METHOD 2: The Core Loop (Now Async)
    # ---------------------------------------------------------
    async def run_task(self, user_input: str) -> str:
        # Put the new task on the active workbench
        self.ram.append_node("user", user_input, status="active")
        
        max_iterations = 5
        current_loop = 0
        
        while current_loop < max_iterations:
            # 1. The Memory Sensor Check
            if self.ram.is_critical():
                # The desk is cluttered. Pause and sweep.
                condensed_state = self.compaction.compact_context(self.ram.active_messages)
                self.ram.clear_compacted_nodes(condensed_state)
            
            # 2. Reason (The LLM Call)
            # We AWAIT the method here instead of defining it here
            action_plan = await self._call_qwen_llm(self.ram.get_working_context())
            
            # 3. Route the Action
            if not action_plan.get("tool_call"):
                # No tools needed. Task is done or it's a regular chat response.
                self.ram.append_node("assistant", action_plan["text"], status="active")
                return action_plan["text"]
                
            tool_name = action_plan["tool_call"]["name"]
            tool_args = action_plan["tool_call"]["args"]
            tool_instance = self.tools.get_tool(tool_name)
            
            # 4. The Blast Gate (Human-in-the-Loop)
            if tool_instance.security_tier == SecurityTier.DESTRUCTIVE:
                # HARD STOP. Pause the loop and alert the FastAPI transport layer.
                return f"SYSTEM_HALT: Tool '{tool_name}' requires human approval."
                
            # 5. Computational Sensors (The Feedback Loop)
            if not tool_instance.verify_preconditions():
                # Catch the error and shove it back into RAM so V can self-correct
                error_msg = f"Observation: Preconditions failed for {tool_name}. Check paths/auth."
                self.ram.append_node("system", error_msg, status="ephemeral")
                current_loop += 1
                continue 
                
            # 6. Act & Observe
            try:
                result = tool_instance.execute(**tool_args)
                # Success! Tag as completed so the Compaction Engine can file it to ROM later
                self.ram.append_node("system", f"Tool Result: {result}", status="completed")
            except Exception as e:
                # Catch actual execution crashes
                self.ram.append_node("system", f"Tool Error: {str(e)}", status="ephemeral")
                
            current_loop += 1
            
        return "Task failed: Exceeded maximum reasoning loops. Compounding error prevented."